# Generated by Django 4.1.3 on 2022-12-01 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grandparent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g1', models.CharField(max_length=255)),
                ('g2', models.IntegerField()),
                ('g3', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(max_length=255)),
                ('p2', models.IntegerField()),
                ('p3', models.TextField(null=True)),
                ('fgrandparent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='author.grandparent')),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.CharField(max_length=255)),
                ('c2', models.IntegerField()),
                ('c3', models.TextField(null=True)),
                ('fparentf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='author.parent')),
            ],
        ),
    ]
