version: "3.8"
services:
  
  django:
    container_name: web_container
    build: .
    ports: 
      - "8000:8000"
    command: bash -c "python manage.py runserver 0:8000"
    volumes: 
      - .:/code
